// Choose which Studio extensions are compiled into this build (docs/extensions.md).
//
// Extensions are first-party TypeScript in extensions/<name>/, listed in
// extensions/catalog.ts. Which of them a build carries is the operator's call:
// extensions.json (committed: the browser-only extensions releases carry) merged with an optional, gitignored
// extensions.local.json, the same way models.local.json works. The result is
// three generated modules:
//
//   build/extensions.names.ts   the names compiled in (Settings validates against it)
//   build/extensions.server.ts  their server halves, for those that have one
//   build/extensions.ui.ts      their Studio halves
//
// Compiling an extension in does not turn it on: each one is also enabled per
// node in Settings, and starts disabled.
//
// BLYG_EXTENSIONS_SHIPPED_ONLY=1 ignores the local file (release builds).
// BLYG_EXTENSIONS=a,b or =all replaces the list (the browser suite uses all;
// "all" means every catalogued extension, never a vendored one).
//
// Registry extensions (docs/extension-registry.md, a proposal): `npm run
// ext:add` vendors a pinned, browser-only tree into the gitignored
// extensions-vendor/<name>/ and records it under "vendored" in
// extensions.local.json. Only the local file names them, so a release build,
// which ignores that file, can never carry one. The build re-hashes each
// vendored tree it compiles and refuses one that differs from its lock.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { EXTENSIONS } from "../extensions/catalog.ts";
import { hashDirectory } from "./registry-tree.ts";

interface Config { compile?: string[]; remove?: string[]; vendored?: Record<string, { sha256?: string }> }
const fail = (msg: string): never => {
  console.error(`build-extensions: ${msg}`);
  process.exit(1);
};
const read = (path: string): Config => {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Config;
  } catch (e) {
    return fail(`${path} is not valid JSON: ${(e as Error).message}`);
  }
};

const known = new Set<string>(EXTENSIONS);
const base = read("extensions.json");
const local = !process.env.BLYG_EXTENSIONS_SHIPPED_ONLY && existsSync("extensions.local.json") ? read("extensions.local.json") : null;
let names = [...(base.compile ?? []), ...(local?.compile ?? [])].filter((name) => !(local?.remove ?? []).includes(name));
const override = process.env.BLYG_EXTENSIONS;
if (override !== undefined) names = override === "all" ? [...known] : override.split(",").map((name) => name.trim()).filter(Boolean);
names = [...new Set(names)].sort();
const vendored = local?.vendored ?? {};
const dir = (name: string) => (vendored[name] ? "extensions-vendor" : "extensions");
for (const name of names) {
  if (known.has(name) && vendored[name]) fail(`"${name}" is both a repository extension and a vendored one; run npm run ext:remove ${name}`);
  if (!known.has(name) && !vendored[name]) fail(`"${name}" is not an extension in extensions/catalog.ts (known: ${[...known].join(", ") || "none"}) or a vendored one in extensions.local.json`);
  if (!existsSync(`${dir(name)}/${name}/ui/index.tsx`)) fail(`${dir(name)}/${name}/ui/index.tsx is missing${vendored[name] ? `; run npm run ext:update ${name}` : ""}`);
  if (vendored[name]) {
    if (existsSync(`extensions-vendor/${name}/server.ts`) || existsSync(`extensions-vendor/${name}/contract.ts`)) fail(`vendored "${name}" has a server half; registry extensions are browser-only`);
    const actual = hashDirectory(`extensions-vendor/${name}`);
    if (actual !== vendored[name].sha256) fail(`extensions-vendor/${name} has changed since it was vendored (tree hash ${actual}, locked ${vendored[name].sha256}); run npm run ext:update ${name}`);
  }
}
const server = names.filter((name) => !vendored[name] && existsSync(`extensions/${name}/server.ts`));

const header = "// Generated by scripts/build-extensions.ts from extensions.json (+ extensions.local.json). Do not edit.\n";
mkdirSync("build", { recursive: true });
writeFileSync("build/extensions.names.ts", header + `export const compiledExtensionNames: readonly string[] = ${JSON.stringify(names)};\n`);
writeFileSync(
  "build/extensions.server.ts",
  header +
    `import type { ServerExtension } from "../src/extensions/server.ts";\n` +
    server.map((name, i) => `import { server as s${i} } from "../extensions/${name}/server.ts";\n`).join("") +
    `export const compiledServerExtensions: readonly ServerExtension[] = [${server.map((_, i) => `s${i}`).join(", ")}];\n`,
);
writeFileSync(
  "build/extensions.ui.ts",
  header +
    `import type { StudioExtension } from "../src/ui/extension-api.ts";\n` +
    names.map((name, i) => `import { extension as e${i} } from "../${dir(name)}/${name}/ui/index.tsx";\n`).join("") +
    `export const compiledExtensions: readonly StudioExtension[] = [${names.map((_, i) => `e${i}`).join(", ")}];\n`,
);
console.log(`build-extensions: ${names.length ? names.join(", ") : "none"} compiled in${local ? " (with extensions.local.json)" : ""}${names.some((name) => vendored[name]) ? ` (vendored: ${names.filter((name) => vendored[name]).join(", ")})` : ""}${override !== undefined ? " (BLYG_EXTENSIONS)" : ""}`);
