// The `wrangler.jsonc` that `npm run init` writes, kept apart from init's
// prompts and wrangler calls so `check-template.ts` can render it and compare
// it with the committed template. The two are written by hand in two places,
// and they drifted once: 0.28 added `nodejs_compat` to the template only, so
// every fresh install failed its first deploy on `No such module "node:crypto"`.

export type InitDeployment = {
  slug: string;
  accountId: string;
  host: string;
  databaseName: string;
  databaseId: string;
  bucketName: string;
};

export function initConfig(d: InitDeployment, date = new Date()): string {
  return `{
  // Generated by \`npm run init\` on ${date.toISOString().slice(0, 10)}.
  //
  // Commit this file — it is your deployment, and version-controlling it is how
  // you can see what changed when something breaks. It holds no secrets: those
  // are Cloudflare Worker secrets, set with \`wrangler secret put\`.
  "name": "blyg-${d.slug}",
  "main": "src/index.ts",
  "compatibility_date": "2026-07-01",

  // Only public HTML uses the shared 60-second cache. The router stays uncached.
  "cache": { "enabled": false },
  "exports": {
    "PublicHtml": { "type": "worker", "cache": { "enabled": true } }
  },
  "compatibility_flags": ["nodejs_compat"],
  "account_id": "${d.accountId}",

  "vars": {
    // "" = domain root. Your blyg is on its own subdomain, so the root is right.
    "MOUNT": ""
  },

  // Check saved XML every minute; poll due subscriptions every 15 minutes.
  // Repair legacy imports and prune expired mentions daily at midnight UTC.
  "triggers": {
    "crons": ["* * * * *", "*/15 * * * *", "0 0 * * *"]
  },

  "routes": [
    // A Custom Domain provisions its own DNS — nothing to add by hand.
    { "pattern": "${d.host}", "custom_domain": true }
  ],

  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "${d.databaseName}",
      "database_id": "${d.databaseId}",
      "migrations_dir": "migrations"
    }
  ],

  "r2_buckets": [
    {
      "binding": "MEDIA",
      "bucket_name": "${d.bucketName}"
    }
  ]

  // Optional: Cloudflare Workers AI, for the \`@cf/…\` models in Settings → AI
  // models. No API key; inference is billed to this account. Nothing uses it
  // until you choose such a model. To enable, add a comma after "r2_buckets"
  // above and uncomment:
  //
  //   "ai": { "binding": "AI" }
}
`;
}
